### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by insomniacc** [insomniacc/PSSnow#16]
Having written and tested this in a windows only environment, I'm fairly certain there will probably be issues when trying to run in other OS's.
Ideally this module needs to be cross compatible.

**Comment by 3vi1** [comment]
I'm not sure there are any issues right now, @insomniacc.  I've been using it under both Windows and Linux, and haven't noticed any issues specific to Linux.

**Comment by insomniacc** [comment]
> I'm not sure there are any issues right now, @insomniacc.  I've been using it under both Windows and Linux, and haven't noticed any issues specific to Linux.

Hey man! I really appreciate the feedback. In all honesty this module has been a bit stale since I started my last job ( haven't had much opportunity to interact with serviceNow altho it's coming in our org!). I defo need to get back into using it and developing it again, expanding it further. Good to know there's nothing major on the Linux side though!

**Comment by 3vi1** [comment]
No problem!

As I've been playing with ServiceNow over the last few months, I've generally been writing the code on my own Linux systems and testing against our dev/qa environments, then running that same code on Windows servers later.  I haven't found a single discrepancy, so I think you can safely close this issue.

If I should find any problems on Linux, I'll be happy to come back and open individual items for them as I discover them.

Thank you again for this really convenient/useful module.
