### ISSUE TITLE
Doesnt work behind corporate firewall.

### ISSUE THREAD

**Issue by zpersichetti12** [insomniacc/PSSnow#53]
**Describe the bug**
Doesnt work behind corporate firewall

**To Reproduce**
1. Import-Module
2. Set-SNOWAuth -Instance "dev123456" -Credential (get-credential)

Can basically fix it by adding a check for corporate firewall then using default credentials / input credentials.
https://bycode.dev/2019/08/22/how-to-use-powershell-invoke-webrequest-behind-corporate-proxy/

Example: 
`

    if([String]::IsNullOrWhiteSpace($Instance)){
        Write-Error "Instance cannot be an empty string" -ErrorAction stop
    }
    
    if($instance -like "https://*"){
        $instance = $instance.replace('https://','')
    }

    if($instance -like "*.service-now.com*"){
        $instance = $instance.split('.') | Select-Object -first 1
    }
    
    $dest = "https://registry.npmjs.org/express"
    $proxy = ([System.Net.WebRequest]::GetSystemWebproxy()).GetProxy($dest)

    #? Aliveness/Hibernation check for developer instances
    $response = Invoke-WebRequest -Uri "https://$Instance.service-now.com/stats.do" -ErrorAction Stop -Verbose:$false -UseBasicParsing -Proxy $proxy -ProxyUseDefaultCredentials
    if($response -and $response.content -like "*Instance Hibernating page*"){
        Throw "This servicenow instance is hibernating. Please wake the instance up and use $($PSCmdlet.MyInvocation.MyCommand.Name) again."
    }
`

**Comment by zpersichetti12** [comment]
I think that may be the only place it needs to be set? Once set there, it seems to carry over and work in CRUD functions (at least the get/sets that Ive tested).

**Comment by insomniacc** [comment]
I've added & tested this on the 'Rate-Limit-Handling' branch, it'll go into the next update along with some other features when I eventually merge that and publish the next version on PSGallery.

Essentially if you provide no additional changes to your existing commands, it should pickup the system proxy and use default credentials. However you can specify -ProxyURI and/or -ProxyCredential on Set-SNOWAuth if you want to supply those too as there's a potential need for some to configure those differently.
