### ISSUE TITLE
Set default or ad-hoc timeout for requests

### ISSUE THREAD

**Issue by ad-85** [insomniacc/PSSnow#54]
**Is your feature request related to a problem? Please describe.**
It appears there is no way to specify a timeout, be it default or per query when using this module. Recently, we had a slowness/degradation in our ServiceNow instance which caused the API to hang for an exceedingly long period - upwards of 5 minutes - before timing out. 

**Describe the solution you'd like**
Ideally, a `TimeoutSec` parameter could be added to the PSSnow cmdlets which passes the integer value through to the `Invoke-RestMethod` / `Invoke-WebRequest` calls to prevent the above behaviour.

**Additional context**
This issue was experienced in Windows Powershell v5.1 on Windows Server 2016 & 2019 hosts.

**Comment by insomniacc** [comment]
I wrote a big comment and it was a load of rubbish lol. Ignore it. I know exactly what you mean, I should have checked the params on invoke-webrequest before I wrote that, it's late and I need sleep lol!
This is a good idea and I'll get it added. I've been busy these past few weeks but looking to get the next update out in the next few days

**Comment by ad-85** [comment]
Ha, I was a bit confused when I read the e-mail notification! Honestly, I was about to write it in myself but thought that you might see it as valuable to have in the official module. I think that it's a perfectly valid approach to have no timeout by default, or quite a long one, but just having a `-TimeoutSec` parameter on the relevant functions that passes it straight through to `Invoke-WebRequest`/`Invoke-RestMethod` if present would probably do the trick.

I've written far worse nonsense when tired myself, don't sweat it! :]
