### ISSUE TITLE
utf8

### ISSUE THREAD

**Issue by johnnystenberg** [insomniacc/PSSnow#57]
Maybe I can't find it, but it doesn't seem like the contenttype is exposed in the cmdlets. How can I specify charset=utf8 as a contenttype? this so that Swedish characters such as åäö are displayed correctly

**Comment by insomniacc** [comment]
Hey, sorry for the delayed response to this, it's been a busy week!
It's not exposed anywhere and you're right, this needs modifying in the content type: https://support.servicenow.com/kb?id=kb_article_view&sysparm_article=KB0789082

If it's defaulted maybe it doesn't need any configurable parameter anywhere, as it should always be utf8? (at least on certain actions like the table api read/write) I'll have a little think about possible consequences of that change and do some testing and add it to the next release.

**Comment by insomniacc** [comment]
@johnnystenberg - Im curious as to which version of servicenow you are running.
I've finally had chance to sit down and work on this one, I've done some testing today on the latest snow version but I'm unable to replicate the issue. The swedish characters I'm pushing into my custom table are returning back ok.

**Comment by insomniacc** [comment]
I'm actually thinking this may have been fixed by another issue I've closed out. I'll get that version published today, it would be great if you could test this for me and let me know if it's resolved.

**Comment by johnnystenberg** [comment]
Hi, Thank you for your reply.

I tested upgrading to pssnow 1.3 and I experienced the same issue.

[image: image.png]
[image: image.png]
[image: image.png]

Addsnownote is just a simple function calling set-snowobject
[image: image.png]

//johnny

Den sön 31 mars 2024 kl 14:06 skrev Tom Piechota ***@***.***>:
