### ISSUE TITLE
The given key 'Content-Type' was not present in the dictionary.

### ISSUE THREAD

**Issue by 3vi1** [insomniacc/PSSnow#59]
I'm not sure if this is a bug with PSSnow or something specific to our ServiceNow instance (I'm a complete newb to SNow):

I can get records from a custom table with no issue, but while trying to update a record in that table I a) have to specify the table on the set command or I receive the error that the table is missing, and b)  Even when specifying the table I receive the error that 'Content-Type' was not present in the dictionary, like so:

```
> get-snowobject -table "u_custom_approver_database" -Sys_ID "2d160c951b2eac942c2cea4abc4bcb06" | set-snowobject -Properties @{u_admin_groups="no"}

Set-SNOWObject: The input object cannot be bound because it did not contain the information required to bind all mandatory parameters:  Table
     
> get-snowobject -table "u_custom_approver_database" -Sys_ID "2d160c951b2eac942c2cea4abc4bcb06" | set-snowobject -table "u_custom_approver_database" -Properties @{u_admin_groups="no"}

Write-Error: 
Line |
8304 |          Invoke-SNOWTableUPDATE -table $Table -Parameters $PSBoundPara …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The given key 'Content-Type' was not present in the dictionary. [https://<our_company>.service-now.com/api/now/v2/table/u_custom_approver_database/2d160c951b2eac942c2cea4abc4bcb06]
```

I wouldn't have expected to have to specify the table on the set, based on the examples, and I don't know how to add the Content-Type key (adding it to the Properties list doesn't work).

**Environment (please complete the following information):**
- Module Version: 1.2.0
- Powershell Version: 7.4.1
- OS: Windows 10
- Servicenow Version: Tokyo

**Comment by insomniacc** [comment]
Hey, sorry I've been away so couldnt get to this earlier...
when piping the object from the Get command, ``` Set-SnowObject ``` looks for the property name 'table' which is typically derived from the ``` sys_class_name ``` property instead.

For example, If I use the command 
``` Get-SNOWObject -Table "sys_user" -Limit 1 ```
OR
``` Get-SNOWUser -limit 1 ```
Both returned objects will have a sys_class_name property with a value of 'sys_user', the set-command leverages that to make the update with the sys_id.

I'm wondering if for some reason the custom table you are addressing is not returning this property? If not, the Set command will not know which table it needs to interact with.
I'm also a little unsure about that content-type error in this context, haven't seen that one before so I'll need to do a bit of testing to see if it can be replicated, if you run the get-object command on it's own, is the record being returned without issue?

**Comment by insomniacc** [comment]
So I just created a custom table in my dev instance and tested this.... it does appear with custom tables at least, the sys_class_name is not returned or part of the fieldset, and I'm also able to replicate the content-type error you mentioned. 
I'll get this fixed and pushed out in a new release.

**Comment by insomniacc** [comment]
Fixed by applying content-type to Invoke-SNOWTableUpdate
@3vi1 - Thanks again for reporting, nice and easy fix on this one, I'm surprised no one else raised it before! I'll published a new version to the gallery later today.
